version: '3.5'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=flightapp
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    ports:
      - 3306:3306
    restart: unless-stopped
    logging:
      options:
        max-size: '10m'

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped
    logging:
      options:
        max-size: '10m'
