version: '3.5'
services:
  mariadb:
    container_name: mariadb_flightapp
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=flightapp
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    ports:
      - 3306:3306
    restart: unless-stopped
    logging:
      options:
        max-size: '10m'

  mongodb:
    container_name: mongodb_flightapp
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped
    logging:
      options:
        max-size: '10m'

  redis:
    container_name: redis_flightapp
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    logging:
      options:
        max-size: '10m'
